### PR TITLE
Added tags

### PR DESCRIPTION
**Pull request by 230Daniel**

### CODE REVIEW

**Review by rikashore — COMMENTED** [review]
Is there a particular reason as to why we're injecting the context factory over directly injecting the context itself?

**Comment by 230Daniel** [comment]
Yes, a DatabaseContext can only have 1 action being performed at a time. If more than 1 action is being performed concurrently it'll throw an exception. Using IDatabaseContextFactory allows us to make a new DatabaseContext for each action, avoiding the potential issue.

The alternative is to have the TagService as transient, in which case a new DatabaseContext will be made for each command anyway. But it'd be messier to have it as transient because of the way we're adding the services to DI.

**Comment by rikashore** [comment]
Everything looks good, I'll merge it in

**Comment by Quahu** [comment]
The proper approach would've been to make your DB context **scoped**, which is the default lifetime `AddDbContext` uses. Every command in Disqord is given its own service scope, hence requesting the `DbContext` from `Context.Services` or injecting via the constructor is the way to go.

`TagService` also seems super redundant, considering its logic is strictly tied to the commands, so they could just implement it directly.

**Pull request merged**
